리뷰 확인
2giwon/DHSample pull request #1
Opened 2020-02-07 04:48 UTC by 2giwon

2020-02-07 08:22 UTC, BeokBeok requested changes

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    protected lateinit var binding: B
접근자를 private 로 변경해주세요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    }
함수를 두 개로 나눌 필요가 없어 보입니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    }
open 함수로 만들어서, 자식 액티비티에서 오버라이드해서 사용하시면 좋을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding, VM : BaseViewModel>(
BaseActivity 에서 남긴 리뷰를 유사하게 적용해주세요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +    abstract class Adapter<A, B : ViewDataBinding>(
가독성을 위해 A 의 타입을 명시해주시면 좋을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +            }
run 과 let 이 혼용되어 있어서 복잡해 보입니다.
좀 더 간결하게 작성할 수 있을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseViewModel.kt
> +    fun Disposable.addDisposable() {
접근자를 추가해주시면 좋을 것 같아요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +@Entity(tableName = "users")
local 에서 사용하는 model 과 remote 에서 사용하는 model 을 분리해주세요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
field 는 안쓰셔도 됩니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        var score: Double,
val 타입으로 변경해 주세요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/local/GithubLocalDataSourceImpl.kt
> +            .subscribeOn(Schedulers.io())
`Schedulers.io()` 를 변수에 설정해서 처리하시면 좋을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/DataSourceModule.kt
> +    single<GithubRepository> { GithubRepositoryImpl(get(), get()) }
factory 로 사용하시면 좋을 것 같아요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/NetworkModule.kt
> +    }
factory 로 사용하시면 좋을 것 같아요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ext/ImageViewExt.kt
> +            .into(this)
3rd party 라이브러리는 wrapper 를 만드시면 좋아요.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/GithubSharedViewModel.kt
> +                    .observeOn(AndroidSchedulers.mainThread())
`AndroidSchedulers.mainThread()` 도 변수를 만들어서 넣어주시면 좋을 것 같아요

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/MainActivity.kt
> +            vpSearch.adapter = adapter
변수 선언 없이 넣을 수 있을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        }
함수로 만들어주시면 좋을 것 같습니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        viewModel.getLikeUser()
onResume 때 호출하는 것은 위험해보입니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
ConstraintLayout 의 자식 뷰는 match_parent 보다 0dp 를 권장합니다.

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/search/SearchUserFragment.kt
> +        viewModel.searchUserLiveData.observe(viewLifecycleOwner, Observer {})
없어도 되지 않나요?

2020-02-07 08:22 UTC, BeokBeok commented on DHSample/app/src/main/res/layout/activity_main.xml
> +                android:text="@={vm.searchQuery}"
검색에 딜레이를 주면 좋을 것 같습니다.

2020-02-08 08:23 UTC, sjjeong requested changes

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/GithubApplication.kt
> +            androidLogger()
디버깅 모드일때만 Logger가 찍히게 해주세요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/GithubApplication.kt
> +            modules(
vararg를 지원하기 때문에 listOf로 하지 않아도 돼요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    protected lateinit var binding: B
@BeokBeok private이면 상속받은 쪽에서 사용할 수 없습니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    }
동감합니다.
private이라서 상속받은 쪽에서는 사용 할 수는 없고 결국 BaseActivity 내부에서만 사용할 수 밖에 없습니다.
그래서 resId용 함수만 있거나 protected로 변경하거나 해야 합니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +        )
한줄로 처리해주세요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +        addObserve()
해당로직은 onViewCreated에서 해줘야 합니다.
뷰 생성과 생성이후 처리를 다르게 해주세요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +    }
activity와 동일한 리뷰 입니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +                }
해당코드는 제거하도록 하는게 좋겠습니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/GithubRepository.kt
> +    fun setLikeUser(user: User): Completable
addLikeUser가 더 좋을 것 같습니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/remote/GithubRemoteDataSourceImpl.kt
> +    override fun searchGithubUser(query: String): Flowable<UserLikeResponse> =
Remote는 단발성이라서 Single을 쓰시면 돼요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/remote/GithubSearchLikeService.kt
> +            clientSecret: String = BuildConfig.GithubClientSecret
쿼리 디폴트값을 사용하는거라면 @GET()에 path에 추가해주세요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/DataSourceModule.kt
> +    single<GithubRepository> { GithubRepositoryImpl(get(), get()) }
Repository라서 single로 해도 상관없습니다.

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/DataSourceModule.kt
> +    single<GithubRepository> { GithubRepositoryImpl(get(), get()) }
모듈을 repository, remote, local나눠서 관리하는게 좋아요

2020-02-08 08:23 UTC, sjjeong commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/search/SearchUserAdapter.kt
> +        @LayoutRes private val layoutResId: Int = R.layout.item_github_user
layoutResId는 넘기지만 onCreateViewHolder를 override해서 의미없는 값이 되버리고 있습니다.
BaseRecyclerView.Adapter와 ViewHolder를 개선해야 합니다.

2020-02-08 14:37 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    protected lateinit var binding: B
BaseActivity 를 상속받는 곳에서 사용하고 있지 않아서 private 로 변경해도 될 것 같다고 판단했는데,
구조상 private 를 사용하지 않는 것이 좋을 것 같네요.

2020-02-08 14:41 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/DataSourceModule.kt
> +    single<GithubRepository> { GithubRepositoryImpl(get(), get()) }
@sjjeong 
현 프로젝트에서는 크게 의미는 없을 것 같지만
Repository 를 single 로 들고 있으면 
모든 Repository 가 앱이 종료될 때까지 메모리에 상주하고 있지 않나요?

2020-02-28 14:58 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/MainActivity.kt
> +            vpSearch.adapter = adapter
밑에서 변수를 사용하고 있어서 한 줄로 하지 않았습니다.

2020-02-28 14:58 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/GithubSharedViewModel.kt
> +                    .observeOn(AndroidSchedulers.mainThread())
변수로 만들면 어떤 장점이 있나요?

2020-02-28 14:58 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/local/GithubLocalDataSourceImpl.kt
> +            .subscribeOn(Schedulers.io())
변수로 적용하면 어떤 장점이 있나요?

2020-03-04 14:35 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    }
protected 로 수정했습니다.

e11932e7dbc38d53023fff75761b1aaa8cadc5d7

2020-03-04 14:37 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +    }
open 변경 후 오버라이드 하도록 수정했습니다.

94cfac6958adc72c1b3ef4ff89460789c7733cc6

2020-03-04 14:39 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding, VM : BaseViewModel>(
동일하게 수정하였습니다.

050dc44e9921eeb7e5faf03e8fca98d1ede0987e
94cfac6958adc72c1b3ef4ff89460789c7733cc6
e11932e7dbc38d53023fff75761b1aaa8cadc5d7

2020-03-04 14:39 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +    abstract class Adapter<A, B : ViewDataBinding>(
수정했습니다.

cdec7f961e38cc6975f11d900f3e41457e096394

2020-03-04 14:40 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +            }
수정했습니다.

8ef8a513fc9e2c769dc1c62a501b8ce56159816c

2020-03-04 14:40 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseViewModel.kt
> +    fun Disposable.addDisposable() {
수정했습니다.
fc92f6ac16ee05afdab9f795eb2bf3963960ec0e

2020-03-04 14:40 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +@Entity(tableName = "users")
분리 적용 했습니다.
06acbf0e29e60e435c7405dd348f3531f06fcdc8

2020-03-04 14:40 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
필드 값을 제거 했습니다.
e1b6d636316b2b36b92420fb998b713627c93baf

2020-03-04 14:41 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        var score: Double,
변경했습니다.
e1b6d636316b2b36b92420fb998b713627c93baf

2020-03-04 14:41 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/local/GithubLocalDataSourceImpl.kt
> +            .subscribeOn(Schedulers.io())
@BeokBeok

2020-03-04 14:43 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        viewModel.getLikeUser()
어디서 호출하는게 좋을까요?

2020-03-04 14:43 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/search/SearchUserFragment.kt
> +        viewModel.searchUserLiveData.observe(viewLifecycleOwner, Observer {})
없으면 transformation이 동작하지 않습니다.

다른 좋은 방법이 있으면 알려주세요

2020-03-04 14:44 UTC, 2giwon commented on DHSample/app/src/main/res/layout/activity_main.xml
> +                android:text="@={vm.searchQuery}"
debounce로 처리하도록 수정했습니다.

386402765e40af67499eb91c0e7c19f1839cab48

2020-03-04 14:44 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/GithubApplication.kt
> +            modules(
수정했습니다.
ab311f4fa1673fb3dc68f1bbf9195b40daea2e5a

2020-03-04 14:44 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseActivity.kt
> +        )
수정했습니다.
050dc44e9921eeb7e5faf03e8fca98d1ede0987e

2020-03-04 14:47 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +        addObserve()
수정했습니다.

866f782d6c57ebc8031cf7d2c7c68f7250ba66f9

2020-03-04 14:49 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/remote/GithubRemoteDataSourceImpl.kt
> +    override fun searchGithubUser(query: String): Flowable<UserLikeResponse> =
수정했습니다.

8114c6cddf74de264fba2131921a62416a445336

2020-03-04 15:11 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/GithubRepository.kt
> +    fun setLikeUser(user: User): Completable
수정했습니다.

7343cea40a4c9c7c09377f6349248b866ae7d7a5

2020-03-04 15:12 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/GithubApplication.kt
> +            modules(
수정했습니다. 
ab311f4fa1673fb3dc68f1bbf9195b40daea2e5a

2020-03-04 15:14 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseFragment.kt
> +    }
동일하게 수정하였습니다.

050dc44e9921eeb7e5faf03e8fca98d1ede0987e
e11932e7dbc38d53023fff75761b1aaa8cadc5d7

2020-03-04 15:15 UTC, 2giwon commented on DHSample/app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
해당코드를 사용하지 않기에 모두 제거했습니다.

9c7c7fe43bcac858f31ed39747db4674609dc7dd

2020-03-04 15:20 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/NetworkModule.kt
> +    }
수정했습니다. 
그런데 어떤 점에서 좋은가요?
9c7c7fe43bcac858f31ed39747db4674609dc7dd

2020-03-04 15:22 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        }
수정했습니다.

9c7c7fe43bcac858f31ed39747db4674609dc7dd

2020-03-09 16:21 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/DataSourceModule.kt
> +    single<GithubRepository> { GithubRepositoryImpl(get(), get()) }
수정했습니다.

df22a1d7e239b500168e30c53c8e4c955be08f79
72c7d2cf5d7ad120e5dd66b23431c26880a7794c
a36be48d4c82e0f6947a5299513f368542262623
5adb3e4ef00a613a923e9ade4b6c84d02c77c198
b79333ee2929380a03d5f4ab587da8d102d7316f

2020-03-10 02:29 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ext/ImageViewExt.kt
> +            .into(this)
수정했습니다.
ab1f5949efa809cf684770910cdb5e55a6842bb0

2020-03-10 02:29 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/search/SearchUserFragment.kt
> +        viewModel.searchUserLiveData.observe(viewLifecycleOwner, Observer {})
transformation 을 제거하고 rxbinding으로 처리하도록 수정했습니다.
19dcd331ea13585b5dbfb81d5aba0699965bfb0c

2020-03-10 02:31 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/base/BaseRecyclerView.kt
> +                }
bindingId를 가져와서 적용하는 방향으로 수정했습니다.
cbdf85c8d89a566048b9b9b54a2c4b9272414615

2020-03-10 02:32 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/remote/GithubSearchLikeService.kt
> +            clientSecret: String = BuildConfig.GithubClientSecret
blocking 이슈로 제거 했습니다.
9e842f61fb6fd578ff9211870bc25f54a64beab2

2020-03-10 02:47 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/GithubApplication.kt
> +            androidLogger()
수정했습니다.
dfddfebe9313cac71a4ae6615dd91720a7738788

2020-03-10 02:48 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/search/SearchUserAdapter.kt
> +        @LayoutRes private val layoutResId: Int = R.layout.item_github_user
수정했습니다.

cbdf85c8d89a566048b9b9b54a2c4b9272414615

2020-03-10 03:16 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/source/local/GithubLocalDataSourceImpl.kt
> +            .subscribeOn(Schedulers.io())
@2giwon 
LocalDataSource 에서 사용하는 스케쥴러 변경 시 유연하게 대처할 수 있습니다.
변수로 적용하셔도 되고 안하셔도 무방합니다.

2020-03-10 03:17 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
`field` 키워드만 제거해주세요.

2020-03-10 03:18 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/di/NetworkModule.kt
> +    }
single 로 하게되면 App이 종료될때까지 메모리에 계속 상주하게 됩니다.
하지만, 본 프로젝트에서는 해당 서비스를 계속 사용하고 있기 때문에 큰 의미는 없는 것 같습니다.

2020-03-10 03:19 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/GithubSharedViewModel.kt
> +                    .observeOn(AndroidSchedulers.mainThread())
스케쥴러 변경에 따른 관리가 편해집니다.
하셔도 되고 하지 않으셔도 될 것 같습니다.

2020-03-10 03:20 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        }
커밋 id 가 본 리뷰와 다른 것 같습니다.

2020-03-10 03:23 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        }
수정할게 많아서 헷갈렸나 봅니다.
아래 리비전 확인 부탁드립니다.

8ee7cdafffd17be6ac4c55caa0fed432746496fb

2020-03-10 03:24 UTC, BeokBeok requested changes

2020-03-10 03:24 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        viewModel.getLikeUser()
해당 데이터를 observe 해서 처리해도 될 것 같습니다.

2020-03-10 04:29 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        viewModel.getLikeUser()
최초 요청은 필요하지 않나요?

2020-03-10 04:51 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/ui/like/UserLikeFragment.kt
> +        viewModel.getLikeUser()
최초 요청은 `onViewCreated` 에서 하시고
이후에는 observe 해서 처리하시면 될 것 같습니다.

2020-03-10 04:57 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
SerializedName도 없어도 되지 않나요?

2020-03-10 05:06 UTC, BeokBeok commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
본 프로젝트에서는 `SerializedName` 이 없어도 무관하지만
릴리즈로 배포 시, 변수가 난독화가 되기 떄문에 가급적이면 사용하시는 것을 권장합니다.

2020-03-10 11:30 UTC, 2giwon commented on DHSample/app/src/main/java/com/egiwon/delieveryherosample/data/User.kt
> +        @field:SerializedName("id")
수정했습니다.
be18564e0f895d5fc54594cbedcde4d775275d08

2020-03-11 01:15 UTC, BeokBeok approved these changes
LGTM:ok_hand:

2020-03-22 13:18 UTC, sjjeong approved these changes

2020-03-22 14:02 UTC, merged